"""initial schema — tables, indexes, and (on Postgres/Supabase) RLS, helper functions, storage bucket.

Revision ID: 0001
Revises: 
Create Date: 2026-09-05 20:25:15.793685
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.db_security import POSTGRES_SECURITY, POSTGRES_SECURITY_DOWN

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('labels', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('audit_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_email', sa.String(length=254), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('resource', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.String(length=400), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_entries_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_entries_created_at'), ['created_at'], unique=False)

    op.create_table('contact_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_messages_created_at'), ['created_at'], unique=False)

    op.create_table('event_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('labels', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('galleries',
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('sample', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('galleries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_galleries_status'), ['status'], unique=False)

    op.create_table('homepage_sections',
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind')
    )
    op.create_table('media_assets',
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('alt', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('caption', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('credit', sa.String(length=240), nullable=False),
    sa.Column('photographer', sa.String(length=240), nullable=False),
    sa.Column('focal_x', sa.Float(), nullable=False),
    sa.Column('focal_y', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key')
    )
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_assets_category'), ['category'], unique=False)

    op.create_table('navigation_items',
    sa.Column('group', sa.String(length=32), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('label', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('external', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['navigation_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('navigation_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_navigation_items_group'), ['group'], unique=False)

    op.create_table('pages',
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('profiles',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('rate_limit_buckets',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('rate_limit_buckets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_limit_buckets_expires_at'), ['expires_at'], unique=False)

    op.create_table('site_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('venues',
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('address', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('directions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('accessibility', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('hours', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('notes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('map_url', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('articles',
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('lead_image_id', sa.Uuid(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sample', sa.Boolean(), nullable=False),
    sa.Column('reading_minutes', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['article_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_image_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_status'), ['status'], unique=False)
        batch_op.create_index('ix_articles_status_published_at', ['status', 'published_at'], unique=False)

    op.create_table('gallery_items',
    sa.Column('gallery_id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('caption', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gallery_id'], ['galleries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gallery_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gallery_items_gallery_id'), ['gallery_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gallery_items_media_id'), ['media_id'], unique=False)

    op.create_table('gallery_translations',
    sa.Column('gallery_id', sa.Uuid(), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gallery_id'], ['galleries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gallery_id', 'locale')
    )
    with op.batch_alter_table('gallery_translations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gallery_translations_gallery_id'), ['gallery_id'], unique=False)

    op.create_table('homepage_section_items',
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('resource', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['homepage_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('homepage_section_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_homepage_section_items_section_id'), ['section_id'], unique=False)

    op.create_table('page_translations',
    sa.Column('page_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('subtitle', sa.String(length=400), nullable=False),
    sa.Column('seo_title', sa.String(length=240), nullable=False),
    sa.Column('seo_description', sa.String(length=400), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'locale')
    )
    with op.batch_alter_table('page_translations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_translations_page_id'), ['page_id'], unique=False)

    op.create_table('videos',
    sa.Column('youtube_id', sa.String(length=11), nullable=True),
    sa.Column('poster_id', sa.Uuid(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('sample', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['poster_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videos_status'), ['status'], unique=False)

    op.create_table('article_translations',
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('subtitle', sa.String(length=400), nullable=False),
    sa.Column('seo_title', sa.String(length=240), nullable=False),
    sa.Column('seo_description', sa.String(length=400), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'locale')
    )
    with op.batch_alter_table('article_translations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_translations_article_id'), ['article_id'], unique=False)

    op.create_table('events',
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('venue_id', sa.Uuid(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('poster_id', sa.Uuid(), nullable=True),
    sa.Column('hero_id', sa.Uuid(), nullable=True),
    sa.Column('video_id', sa.Uuid(), nullable=True),
    sa.Column('sample', sa.Boolean(), nullable=False),
    sa.Column('credits', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['event_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hero_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['poster_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_status'), ['status'], unique=False)
        batch_op.create_index('ix_events_status_published_at', ['status', 'published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_venue_id'), ['venue_id'], unique=False)

    op.create_table('video_translations',
    sa.Column('video_id', sa.Uuid(), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('subtitle', sa.String(length=400), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'locale')
    )
    with op.batch_alter_table('video_translations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_translations_video_id'), ['video_id'], unique=False)

    op.create_table('event_gallery_items',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'media_id')
    )
    with op.batch_alter_table('event_gallery_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_gallery_items_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_gallery_items_media_id'), ['media_id'], unique=False)

    op.create_table('event_sessions',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_sessions_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_sessions_starts_at'), ['starts_at'], unique=False)
        batch_op.create_index('ix_event_sessions_status_starts_at', ['status', 'starts_at'], unique=False)

    op.create_table('event_translations',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('audience', sa.String(length=240), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('subtitle', sa.String(length=400), nullable=False),
    sa.Column('seo_title', sa.String(length=240), nullable=False),
    sa.Column('seo_description', sa.String(length=400), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'locale')
    )
    with op.batch_alter_table('event_translations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_translations_event_id'), ['event_id'], unique=False)

    op.create_table('event_ticket_links',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('price', sa.String(length=40), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('note', sa.String(length=240), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['event_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    # ### end Alembic commands ###
    if op.get_bind().dialect.name == 'postgresql':
        for statement in POSTGRES_SECURITY:
            op.execute(statement)


def downgrade() -> None:
    if op.get_bind().dialect.name == 'postgresql':
        for statement in POSTGRES_SECURITY_DOWN:
            op.execute(statement)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_ticket_links')
    with op.batch_alter_table('event_translations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_translations_event_id'))

    op.drop_table('event_translations')
    with op.batch_alter_table('event_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_event_sessions_status_starts_at')
        batch_op.drop_index(batch_op.f('ix_event_sessions_starts_at'))
        batch_op.drop_index(batch_op.f('ix_event_sessions_event_id'))

    op.drop_table('event_sessions')
    with op.batch_alter_table('event_gallery_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_gallery_items_media_id'))
        batch_op.drop_index(batch_op.f('ix_event_gallery_items_event_id'))

    op.drop_table('event_gallery_items')
    with op.batch_alter_table('video_translations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_translations_video_id'))

    op.drop_table('video_translations')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_venue_id'))
        batch_op.drop_index('ix_events_status_published_at')
        batch_op.drop_index(batch_op.f('ix_events_status'))
        batch_op.drop_index(batch_op.f('ix_events_category_id'))

    op.drop_table('events')
    with op.batch_alter_table('article_translations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_translations_article_id'))

    op.drop_table('article_translations')
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_status'))

    op.drop_table('videos')
    with op.batch_alter_table('page_translations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_translations_page_id'))

    op.drop_table('page_translations')
    with op.batch_alter_table('homepage_section_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_homepage_section_items_section_id'))

    op.drop_table('homepage_section_items')
    with op.batch_alter_table('gallery_translations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gallery_translations_gallery_id'))

    op.drop_table('gallery_translations')
    with op.batch_alter_table('gallery_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gallery_items_media_id'))
        batch_op.drop_index(batch_op.f('ix_gallery_items_gallery_id'))

    op.drop_table('gallery_items')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index('ix_articles_status_published_at')
        batch_op.drop_index(batch_op.f('ix_articles_status'))
        batch_op.drop_index(batch_op.f('ix_articles_category_id'))

    op.drop_table('articles')
    op.drop_table('venues')
    op.drop_table('site_settings')
    with op.batch_alter_table('rate_limit_buckets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_limit_buckets_expires_at'))

    op.drop_table('rate_limit_buckets')
    op.drop_table('profiles')
    op.drop_table('pages')
    with op.batch_alter_table('navigation_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_navigation_items_group'))

    op.drop_table('navigation_items')
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_assets_category'))

    op.drop_table('media_assets')
    op.drop_table('homepage_sections')
    with op.batch_alter_table('galleries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_galleries_status'))

    op.drop_table('galleries')
    op.drop_table('event_categories')
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_messages_created_at'))

    op.drop_table('contact_messages')
    with op.batch_alter_table('audit_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_entries_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_entries_actor_id'))

    op.drop_table('audit_entries')
    op.drop_table('article_categories')
    # ### end Alembic commands ###
